### ISSUE TITLE
No TX or RX against commercial devices and gr-lora from rpp0

### ISSUE THREAD

**Issue by FlUxIuS** [martynvdijke/gr-lora_sdr#4]
Hi,

Thanks for the port to 3.8 version of @tapparelj we can directly try.  I shortly tried the project and tested the RX against TX that are working perfectly. Nevertheless, against gr-lora from rpp0 (https://github.com/rpp0/gr-lora) no uplink frame gets detected using the same config (SF, BW, freq), and neither with a Dragino LG308 gateway, and the RX part of the project doesn't see uplink packets coming from sensors I have including a LoRa shield to easily force the config with Arduino SDK. Only if I conjugate downlink, some garbage happens but not the original text.

Does it work on the original 3.7 version? Or maybe I'm missing another thing? The RX and TX I'm using are taken from the app directory, I only adapted the frequency to match the 868 MHz in Europe, used it with one channel like 868.1MHz, CR=4, SF=7, BW=125kHz, and adjusted the TX_gain to see something in my receiver using a waterfall and FFT. 

Thanks in advance!

**Comment by tapparelj** [comment]
Hi,

The version 3.7 was tested using both link directions with a LoRa chip RFM95W (https://cdn.sparkfun.com/assets/learn_tutorials/8/0/4/RFM95_96_97_98W.pdf). If nothing gets detected I would investigate the configuration of the network identifiers as their default values might not match with ours, which are value 8 and 16. For the receiver you can set them in lib/frame_sync_impl.cc( in the constructor). For the transmitter you can change them in lib/modulate_impl.cc (in general_work()). 

What are you meaning by conjugate downlink?

Let me know if your network identifiers are the same and if it doesn't solve your issue can you attach a picture of the GNU Radio flowgraphs you have modified.

**Comment by FlUxIuS** [comment]
Hi @tapparelj,

So the flowgraph has been modifying as follows to match EU frequency plan:
![grlorasdr_TX](https://user-images.githubusercontent.com/715195/105529860-52b92c00-5ce7-11eb-9943-d86f2e4c7342.png)

I could make the TX work with `gr-lora` from @rpp0 by doing a very basic flowgraph on the RX side and with a 250 kHz samp rate:
![grlorasdr_to_grlorarpp0](https://user-images.githubusercontent.com/715195/105530277-da9f3600-5ce7-11eb-8046-c9016820e714.png)

But it seems to get desync after some packets. I'll try with two different computers because I generally manage to use `gr-lora` with multiple freqs and SF using a 2 MHz bandwidth and few optimizations

Using the TX flowgraph, I don't see anything on the SX1301 and SX1257 of the Dragino LG308. 

About the RX, the flowgraph is kind of the same as one of your apps like the TX one:
![grlorasdr_RX](https://user-images.githubusercontent.com/715195/105530735-79c42d80-5ce8-11eb-930d-b89205cc2342.png)

But doesn't see the signal sent by the Microchip RN2483, neither the Dragino LoRa Shield. 

Here is a sample of the Microchip RN2483 with some dumb 0x45 bytes: 
https://drive.google.com/file/d/1PHUJ4WSvJh8ysPSzhUYuXgj7IBr6vdnG/view?usp=sharing

**Comment by tapparelj** [comment]
Hi,
I just tested the samples you sent and found out that the sync words of the Microchip RN2483 are 24 and 32. By editing them in the previously mentioned locations, the frames are correctly detected . 
![image](https://user-images.githubusercontent.com/66671413/105685200-190a4000-5ef6-11eb-8d0e-54d0cee6cc09.png)

If you don't know what they are from the chip datasheets, you can easily find their values by adding the "cout" line after the case NET_ID1 (in lib/frame_sync_impl.cc ~line 400):
```
switch (symbol_cnt) {
    case NET_ID1:{
        std::cout<<"net id 1 = "<<bin_idx<<std::endl;
```
Then modifying the value net_id_1 accordingly, compiling and adding the same line in the case NET_ID2.

**Comment by martynvdijke** [comment]
Hi,

I am not sure how, but I completely missed this issue and PR, sorry for that.
Is the issue now fixed ?

**Comment by FlUxIuS** [comment]
Thanks @tapparelj! I'll try that at least next week :)

Do you have also an idea of the problem for the TX part, to be seen on the Dragino GW. I was looking with a LG308 at the time.

Thanks in advance!
